### PR TITLE
Streamlit update

### PR DESCRIPTION
**Pull request by adhamarif**
Hi everyone!

Here are few updates from me.
1. Documentation is added in the code.
2. Remove `day_label.py` file because we dont use the file anymore. We now mainly use streamlit as our GUI.
3. **[IMPORTANT]** The bug for the save file now has been fixed. Every .csv files created will be saved in the `datasets` folder. So we will have the better data structure.

I need everyone to test the update here especially the point number 3, because I need to know if it's run perfectly on Windows/MacOS/Linux or if it has any problem with any operating system.

### CODE REVIEW

**Comment by adhamarif** [comment]
Issue #43 resolved

**Review by till-teb — APPROVED** [review]

**Comment by till-teb** [comment]
I had no problem and no error. I deleted the data set and try, if the code creates a new one and it does. I m really happy with the streamlit dashboard. As I already said, **it runs well without any error occurring on macOS**. 


GREAT ADHAM 👍

**Comment by till-teb** [comment]
hahah wow, now I updated streamlit and **I can not run the main.py anymore** hahah cry....

**Comment by till-teb** [comment]
> hahah wow, now I updated streamlit and **I can not run the main.py anymore** hahah cry....

I got that error : 

`cannot import name 'builder' from 'google.protobuf.internal' (/Users/tillteb/opt/anaconda3/envs/Semester_2/lib/python3.8/site-packages/google/protobuf/internal/__init__.py)`

I´m trying to fix that now.

**Pull request merged**
