### PR TITLE
subcategory added to dataset

### PR DESCRIPTION
**Pull request by adhamarif**
bug for subcategory fixed. #36

### CODE REVIEW

**Comment by adhamarif** [comment]
delete function is created, and it used uuid library to create unique key.

Please install the library to run the code.

```python
pip install uuid
```

**Comment by l4nz8** [comment]
ok we can merge the branch

**Comment by adhamarif** [comment]
the uuid library is used to create temporary unique key, when the delete function is used. It would be useful, so that we can delete the intended row.

Example:

item | price | category | temp_unique_key
apple | 0.50 | Foods | 1022
orange | 0.60 | Foods | 5024
apple | 1.00 | Transportation | 3499

If we want to delete apple from row 3, we can simply use the `temp_unique_key` instead of creating combination of `apple + 1.00 + Transportation`

**Review by l4nz8 — APPROVED** [review]
ok we can merge the branch, it will fit

**Comment by adhamarif** [comment]
Thanks!

**Pull request merged**
