### PR TITLE
small fix

### PR DESCRIPTION
**Pull request by till-teb**
fix that by taking away the: _"icon="*""_ for saving in the dataset and also for deleting an entry. 
Bildschirmfoto 2023-02-08 um 17 03 22

### CODE REVIEW

**Comment by l4nz8** [comment]
if you want to use emojis with python prints please use unicode characters as described in this article:
https://medium.com/analytics-vidhya/how-to-print-emojis-using-python-2e4f93443f7e

unicode list:
https://unicode.org/emoji/charts/full-emoji-list.html

**Comment by adhamarif** [comment]
That works perfectly fine before. The error there stated that there is no icon in `st.info()`, but the documentation here https://docs.streamlit.io/library/api-reference/status/st.inf stated that there is icon argument and we need to use single emoji like this "🚨", "🔥", "🤖".

Is it okay when you @l4nz8 test the code before?  Because last time we both together test the input and it works great

I need to know what the problem is actually here, so that we can decide to fix this or just remove the emoji from all the pages

**Review by l4nz8 — COMMENTED** [review]
i have fixt the problem with unicode

**Review by l4nz8 — APPROVED** [review]
fixt

**Pull request closed without merging**
