### PR TITLE
Improvement of blemishes 

### PR DESCRIPTION
**Pull request by till-teb**
- added **_matplotlib_** to `requirements`
- added two small plots ( @l4nz8  I know, you wanted to do that page, is that still correct? )
- added new categorie:
`Financial fees` and `living area`
because: 
If you want to create a new entry e.g. for your apartment rent, there was no correct category. 

Tell me your opinion

### CODE REVIEW

**Comment by till-teb** [comment]
@velixko  I think we have to update the `two new categories` in the `data generator`.

Because the `data generator` was your coding project, do you want to add the columns? 

- If not, let me know so I can fix that. 

Thanks

**Comment by adhamarif** [comment]
Hi,
the code runs perfectly good (especially in `dashboard.py`)! Great job!

Only a reminder here that we already delete the file `user_input.py` and `expenses_dataset.csv` due to this reason:
- `user_input.py` code is no longer used, because we mainly used streamlit now. Resolved in #47 
- `expenses_dataset.csv` should not be tracked by github. Discussed in #28 

I see that that those file are still tracked by github in this pull request. As alternative, maybe I could suggest for you to either:
- Delete the file locally from your laptop, or
- not using `git add --all` if git still tracked the unnecessary file.

I dont know if this is really the solution but this is what I would recommend.

**Comment by adhamarif** [comment]
The unused files were deleted in #50. Nice work @till-teb !

**Comment by velixko** [comment]
i can update the data generator, no problem :)

**Pull request merged**
